# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Instagram Handle'),
        ),
    ]
