# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170109_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='\n            Designates whether this user should be treated as active.\n            Unselect this instead of deleting accounts.\n        ', verbose_name='active'),
        ),
    ]
