# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(max_length=255, verbose_name='Graph')),
                ('accessed_via', models.PositiveSmallIntegerField(verbose_name='Accessed Via')),
                ('time_spent', models.DurationField(verbose_name='Time Spent')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
